# Generated by Django 3.1 on 2020-09-28 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('card_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='current_balance',
            field=models.CharField(max_length=100000000, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='mobile_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='occupation',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='recorded_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='record',
            name='residence',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
