# Generated by Django 3.1 on 2020-08-29 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('residence', models.CharField(max_length=50, null=True)),
                ('occupation', models.CharField(max_length=150, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
