# Generated by Django 3.1 on 2020-08-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='current_balance',
            field=models.CharField(max_length=100000000, null=True),
        ),
    ]
